# _config.yml
title: Radhwen Saidi - Data Scientist & ML Engineer 
description: Portfolio professionnel de Radhwen Saidi, expert en Data Science et Machine Learning
theme: jekyll-theme-minimal
logo: /assets/img/profile.jpg
